import { Background } from "../typings/background.d"
import { SkillEnum } from "../typings/skill.d"

export const GetCharacterBackground = (): Background => {
    return {
        name: 'back',
        descrption: [
            'Asura grew up in a small (New Baator, ~80 people), out of the way town. Most of the residents were tieflings, which was the reason for its location. While most people were mainly indifferent towards the tieflings, there were enough extremists harboring ill intentions so as to discourage them from traveling alone or venturing far, just to be safe. If you did, your best bet was to move in a large group and look high class, although that could attract another kind of unwanted attention.',
            'Traveling was rarely an issue however, as New Baator was self-sufficient. Every once in a while, a group would make a trip to a neighboring city to trade and resupply niche tools or medicines that the town couldn’t produce on its own, but that was about it. When he was 12 years old, one such trip failed to return by the expected date. A week went by and the town sent off a second, smaller party to investigate. Tensions rose as the days went by, until one night Asura woke up to screams on the streets and fire on the horizon. He rushed to the window and saw chaos on the streets. Hooded men were everywhere, fighting the locals that stood their ground while others fled. His mother (Nithmine, a tiefling) barged into his room, shut the blinds and pulled him to the living room in a rush. His father (Farlen Shadowcloud,a slender high elf) was already waiting with an axe in his hand, with a resolute look on his face.',
            'The three of them fled through the backdoor. His father had seen some of the hooded men on horses, patrolling for stragglers, so the plan was to make a beeline for the forest where they’d have a harder time maneuvering. They lived near the outskirts of the town, so for a moment, it seemed like they could make it; but they were spotted by a lone rider who rushed to meet them. Farlen stood his ground to face him while he shouted at them to keep running, and they did. But he wasn’t a warrior, and he never stood a chance. Asura turned in time to see the attackers sword make a deep cut on his fathers neck, but not before he managed to hit one of the horses legs with his axe, making it topple over. They kept on running and reached the edge of the forest while they heard the rider cursing and rustling as he got up.',
            'His mother must have seen the scene as well, because despite her gutted expression, she urged him to keep going. Arrows started trickling in, but the hooded man had to pause to shoot so they started gaining ground. Before they managed to get out of range, he shot true, and an arrow pierced his mother’s side. He tried to support her as they kept moving forward, but it was a matter of time before the man caught up to them now. When he did, Asura could see he was dressed in garments that concealed his entire body, leaving only the eyes exposed. Still, he could have sworn he was grinning. He walked over and pushed Asura to the side while he grabbed the Nithmine by the shoulder. She didn’t have the strength to resist. He seemed to examine her wound, but after a moment he let out a sound of displeasure and let her drop.',
            "Asura had been too shocked to move, and only then did he realize he was covered in her blood. As the man approached him, picked him up by the arm and started dragging him like you would a misbehaving dog. Asura was not a strong kid, and his efforts to reach for his mothers limp body only served to earn him a slap that left his ears ringing. In just a few seconds, the emotions he was trying to repress started spilling. He started crying profusely, but he clenched his jaw and didn’t let out a sound. He was boiling with anger, and convinced this was all done to them because of their bloodline. He half cursed, half pleaded at Baphomet to do something to help fix the mess he had (indirectly) caused, and to his absolute surprise, something answered. A new power swelled inside him, and he knew what to do. He gently placed his hand on the man's side, as if for support. He focused his hate on him, and let the magic flow through his arm and crush the man’s ribs. He let out a piercing shout as the air left his lungs, and fell, grabbing his side. Asura lined up his shot, and let out a second blast, and then a third, for good measure.",
            "He then ran to his mother, who had started weakly crawling in his direction. He put her upright and hugged her gently so as not to hurt her. She was about to die and they both knew it. She used her last moments to tell him his father and her loved him, and that he was a resourceful boy and he would be all right. That he must leave her behind and run. He promised he would, but stayed with her until she drew her last breath. His head was swirling but there was no time for doubt. He took his mothers silver pendant (his fathers craftsmanship) and went back to where her murderer lay dead. A quick search revealed a dagger, which he used to start cutting his clothes open to better go through his belongings. This revealed a strange tattoo on the inside of his arm, the shape was not familiar to him, but it was burnt in his memory as his only lead on the perpetrators identity. After just a few moments he heard chatter and footsteps approaching in the distance. He gathered what little valuables he found (a longsword, a dagger and a coin pouch) and ran away.",
            "He spent the next three years wandering from city to city, not daring to stay in one place for too long. The first six months were the roughest, but he started off by selling the weapons and securing himself food and clothes so he didn’t have to worry about that straight away. He tried different ways of begging in the street and landed on singing as his best resource. A passing musician took pity on him (and saw an opportunity), and offered him to be his assistant in exchange for food. They did this for a year, during which they performed in various inns and campfires. Asura got tips from time to time, and managed to save a little bit and buy a lute (and was taught how to play it). By the time he was 13 he decided he was ready to be on his own again and bid a warm farewell to the musician, and they parted ways. Using what he learned and aided by his magic, he managed to do decent for himself and keep a humble but stable lifestyle.",
            "When he was 15 his life took a turn. He befriended a merchant and was traveling with his caravan (he often joined a group when moving from city to city, for safety) when a group of bandits attacked. Most civilians took cover but he had been exploring the powers that had awakened in him and, compelled to fight, drew out his sword and faced the enemy. Unbeknownst to him, the mercenaries protecting the caravan worked for no other than the Zulu guild, and him joining the fight was duly noted by Bröm, one of its members. He approached Asura to introduce himself after the fight and during the rest of the trip they became fast friends. Bröm convinced Asura to go back to the guild with him.",
            "Asura was too young for the guild to accept him as a mercenary, but they welcomed him with open arms, and offered him a job as regular staff (to help with cooking, cleaning, whatever was needed at the moment) in exchange for food and lodging. This was a very generous offer (influenced by Bröm no doubt) and he could not think of a reason to refuse. It took some time to get used to a sedentary lifestyle, but he realized that being constantly surrounded by mercenaries, he could start letting go of his paranoia. Slowly he began feeling safe again.",
            "Bröm knew Asura would want to work as a mercenary, and had no doubt he’d be a good one, but was worried about the origin of his powers. So he took it upon himself to start training Asura in general warfare, and to help him look for new avenues to gain strength, with the help of fellow Zulu members. One such member was the paladin Yuri, who started by teaching Asura the basic theory behind the various Oaths. When he learnt about the Oath of Vengeance, he immediately knew that was his path. Yuri had sworn the Oath of the Crown, but the basis for most oaths was the same, so he spent a lot of time helping Asura understand what he was getting into and build his foundations.",
            "Asura trained hard, but he didn’t have a privileged physique, and gaining muscle was an uphill battle, so he relied on his eldritch powers to make up the difference. Seeing how worried that made Bröm though, he agreed to develop them only as much as he deemed absolutely necessary. After preparing for a couple of years, he finally took his oath when he turned 18, and the guildmaster agreed to let him start working as a mercenary despite his age. But they made him start with the smallest jobs available, so he would slowly get a feel of how things worked on the field. When he got back from completing his first mission, Bröm was brimming with pride and he gifted him a Stone of Good Luck he’d been saving for this moment. Asura thought it was all extremely symbolic and felt the need to push back tears to avoid looking like a wimp in front of the guild. Both Yuri and Bröm insisted this warranted one of Zulus famous feasts and a massive party was thrown to celebrate Asura’s coming of age. He’s been in service ever since (now 22 yo). He has a lot of good friends now, and although he doesn’t see eye to eye with every guild member, he sees the guild as a whole as family.",
            "He’s always wanted to get back at the butchers of New Baator, and as he keeps getting stronger that’s no longer a wild dream but a very real possibility. He’s been doing everything he can to get ready for it. He’s been climbing the guild's ranks, and although all he has to go off is the memory of that man’s tattoo, Rocko has promised to help him find information about the group and their whereabouts. Asura’s also been funneling the lion’s share of his earnings into a Mithril Plate that one of the guild’s blacksmiths said he was willing to make for him, given enough time and resources. With both of those things moving in the background, he is eager for a new challenge. One that will help push him to new heights, and a stronger attunement to his oath.",
        ],
        features: [
            'A good entertainer is versatile, spicing up every performance with a variety of different routines. Your routines are: Instrumentalist, Singer, Storyteller',
            '<strong>By Popular Demand</strong><br/>',
            "You can always find a place to perform, usually in an inn or tavern but possibly with a circus, at a theater, or even in a noble's court. At such a place, you receive free lodging and food of a modest or comfortable standard (depending on the quality of the establishment), as long as you perform each night. In addition, your performance makes you something of a local figure. When strangers recognize you in a town where you have performed, they typically take a liking to you."
        ],
        toolProficiencies: ['Disguise kit', 'Lute'],
        skillProficiencies: [ SkillEnum.Perception, SkillEnum.Deception ]
    }
}