export enum SpellEnum {
  AbsorbElements,
  Aid,
  Alarm,
  ArcaneEye,
  ArmorOfAgathys,
  AnimateObjects,
  Augury,
  Banishment,
  Bane,
  BestowCurse,
  Bless,
  Blur,
  BrandingSmite,
  Ceremony,
  Clairvoyance,
  Command,
  CompelledDuel,
  ComprehendLanguages,
  Contingency,
  ContactOtherPlane,
  ContinualFlame,
  Counterspell,
  CureWounds,
  Creation,
  Darkness,
  DetectEvilAndGood,
  DetectMagic,
  DetectPoisonAndDisease,
  DimensionDoor,
  Disintegrate,
  DispelMagic,
  DivineFavor,
  Divination,
  DominatePerson,
  EldritchBlast,
  EnhanceAbility,
  Etherealness,
  Fabricate,
  FeatherFall,
  Fireball,
  FindSteed,
  FindFamiliar,
  FloatingDisk,
  Fly,
  Forcecage,
  GentleRepose,
  GreaterInvisibility,
  GiftOfAlacrity,
  GlyphOfWarding,
  GlobeOfInvulnerability,
  Heroism,
  HoldPerson,
  HoldMonster,
  HuntersMark,
  HypnoticPattern,
  Identify,
  IllusoryScript,
  Invisibility,
  InstantSummons,
  Knock,
  LesserRestoration,
  LocateObject,
  MagicCircle,
  MagicWeapon,
  MagicMissile,
  MagicJar,
  MagicMouth,
  MageHand,
  MagnifyGravity,
  MindSliver,
  MinorIllusion,
  MirageArcane,
  MistyStep,
  PhantomSteed,
  PlanarBinding,
  PlaneShift,
  Polymorph,
  Prestidigitation,
  PrayerOfHealing,
  PrivateSanctum,
  ProtectionFromEvilAndGood,
  ProtectionFromEnergy,
  ProtectionFromPoison,
  PurifyFoodAndDrink,
  RopeTrick,
  RemoveCurse,
  ResilientSphere,
  Sanctuary,
  SearingSmite,
  SickeningRadiance,
  SilveryBarbs,
  SickeningRadiance,
  Simulacrum,
  ShapeWater,
  Shield,
  ShieldOfFaith,
  SleetStorm,
  SpeakWithDead,
  Suggestion,
  Scrying,
  SynapticStatic,
  TelepathicBond,
  Teleport,
  TinyHut,
  ThunderousSmite,
  Tongues,
  TrueSeeing,
  UnseenServant,
  WallOfForce,
  WallOfFire,
  WallOfStone,
  WardingBond,
  WaterBreathing,
  Web,
  WrathfilSmite,
  ZoneOfTruth,
}

type SpellDamage = {
  damageType?: string,
  damageAtCharacterLevel?: { [key: string]: string }
}

export type Spell = {
    spellEnum?: SpellEnum,
    name: string,
    description: string,
    range: string,
    components: string,
    material: string,
    duration: string,
    higherLevel?: string,
    ritual: boolean,
    concentration: boolean,
    castingTime: string,
    level: number,
    damage?: SpellDamage,
    classes?: ClassEnum[],
}

export type SpellSlot = {
  level: number,
  amount: number,
}