export enum SpellEnum {
  AbsorbElements,
  Aid,
  Alarm,
  ArmorOfAgathys,
  Bane,
  Bless,
  Blur,
  BrandingSmite,
  Ceremony,
  Command,
  CompelledDuel,
  ComprehendLanguages,
  Contingency,
  ContactOtherPlane,
  Counterspell,
  CureWounds,
  Darkness,
  DetectEvilAndGood,
  DetectMagic,
  DetectPoisonAndDisease,
  DivineFavor,
  Divination,
  EldritchBlast,
  FeatherFall,
  Fireball,
  FindSteed,
  FindFamiliar,
  FloatingDisk,
  Forcecage,
  GentleRepose,
  GiftOfAlacrity,
  Heroism,
  HoldPerson,
  HuntersMark,
  HypnoticPattern,
  Identify,
  IllusoryScript,
  Invisibility,
  InstantSummons,
  LesserRestoration,
  LocateObject,
  MagicWeapon,
  MagicMissile,
  MageHand,
  MagnifyGravity,
  MindSliver,
  MinorIllusion,
  MistyStep,
  Polymorph,
  Prestidigitation,
  PrayerOfHealing,
  ProtectionFromEvilAndGood,
  ProtectionFromPoison,
  PurifyFoodAndDrink,
  Sanctuary,
  SearingSmite,
  SickeningRadiance,
  SilveryBarbs,
  SickeningRadiance,
  Simulacrum,
  ShapeWater,
  Shield,
  ShieldOfFaith,
  SleetStorm,
  Suggestion,
  SynapticStatic,
  TinyHut,
  ThunderousSmite,
  UnseenServant,
  WallOfForce,
  WardingBond,
  WrathfilSmite,
  ZoneOfTruth,
}

type SpellDamage = {
  damageType?: string,
  damageAtCharacterLevel?: { [key: string]: string }
}

export type Spell = {
    spellEnum?: SpellEnum,
    name: string,
    description: string,
    range: string,
    components: string,
    material: string,
    duration: string,
    higherLevel?: string,
    ritual: boolean,
    concentration: boolean,
    castingTime: string,
    level: number,
    damage?: SpellDamage,
    classes?: ClassEnum[],
}

export type SpellSlot = {
  level: number,
  amount: number,
}